replicatCount: 1

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

minio:
  enable: true
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: image-dandelion-grass

service:
  type: NodePort
  port:
    - 9000
    - 9001
  nodePort:
    - 30900
    - 30901
