FROM python:3.9.18-slim

WORKDIR /mlflow

RUN pip install -U pip --upgrade pip
RUN pip install mlflow
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --user -r /tmp/requirements.txt

ENV BACKEND_URI sqlite:///mlflow.db
ENV MLFLOW_EXPERIMENT_NAME="DINOv2_Classifier"

EXPOSE 6000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "6000"]