apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow
  labels:
    app: mlflow
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 6000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: mlflow
