{
 "title": "FastAPI Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total POST Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "request_count_total{method=\"POST\"}",
     "legendFormat": "Total POST requests count"
    }
   ]
  },
  {
   "title": "Total GET Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "request_count_total{method=\"GET\"}",
     "legendFormat": "Total GET requests count"
    }
   ]
  },
  {
   "title": "Request Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[1m]) / rate(request_latency_seconds_count[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    { "expr": "rate(request_count_total[1m])", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  }
 ]
}