{
 "title": "Streamlit Metrics Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Page Views",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "streamlit_page_views_total", "legendFormat": "Page Views" }
   ]
  },
  {
   "title": "Pages Views Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Views/s" }
   ],
   "targets": [
    {
     "expr": "rate(streamlit_page_views_total[1m])",
     "legendFormat": "Views per second"
    }
   ]
  },
  {
   "title": "Total Predict Button Clicks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "predict_button_clicks_total", "legendFormat": "Button Clicks" }
   ]
  },
  {
   "title": "Button Clicks Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Clicks/s" }
   ],
   "targets": [
    {
     "expr": "rate(predict_button_clicks_total[1m])",
     "legendFormat": "Clicks per second"
    }
   ]
  }
 ]
}