apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - name: http
      port: {{ .Values.service.ports[0] }}
      targetPort: 8501
    - name: second
      port: {{ .Values.service.ports[1] }}
      targetPort: 8502
  type: {{ .Values.service.type }}
