
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.minio.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.minio.secretKey }}
            - name: S3_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
