apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: nnmp020395/fastapi-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: S3_ENDPOINT
              value: http://minio:9000
          volumeMounts:
            - name: model-volume
              mountPath: /app/dinov2_classifier.pth
      volumes:
        - name: model-volume
          emptyDir: {}
