
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
