apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
  labels:
    io.kompose.service: airflow-scheduler
    app.kubernetes.io/managed-by: Helm
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: airflow-scheduler
    spec:
      containers:
        - args:
            - scheduler
          env:
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS
              value: content-type, origin, authorization, accept
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS
              value: GET, POST, OPTIONS, DELETE
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS
              value: '*'
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: _PIP_ADDITIONAL_REQUIREMENTS
          image: airflow-scheduler
          livenessProbe:
            exec:
              command:
                - airflow jobs check --job-type SchedulerJob --hostname "${HOSTNAME}"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: airflow-scheduler
          securityContext:
            runAsGroup: 0
            runAsUser: 50000
          volumeMounts:
            - mountPath: /opt/airflow/plugins
              name: airflow-scheduler-claim2
            - mountPath: /mlflow
              name: airflow-scheduler-claim4
      restartPolicy: Always
      volumes:
        - name: airflow-scheduler-claim2
          persistentVolumeClaim:
            claimName: airflow-scheduler-claim2
        - name: airflow-scheduler-claim4
          persistentVolumeClaim:
            claimName: airflow-scheduler-claim4
