apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-triggerer
  name: {{ .Release.Name }}-airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      containers:
        - args:
            - triggerer
          env:
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS
              value: content-type, origin, authorization, accept
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS
              value: GET, POST, OPTIONS, DELETE
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS
              value: '*'
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: _PIP_ADDITIONAL_REQUIREMENTS
          image: airflow-triggerer
          livenessProbe:
            exec:
              command:
                - airflow jobs check --job-type TriggererJob --hostname "${HOSTNAME}"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: airflow-triggerer
          securityContext:
            runAsGroup: 0
            runAsUser: 50000
          volumeMounts:
            - mountPath: /opt/airflow/plugins
              name: airflow-triggerer-claim2
            - mountPath: /mlflow
              name: airflow-triggerer-claim4
      restartPolicy: Always
      volumes:
        - name: airflow-triggerer-claim2
          persistentVolumeClaim:
            claimName: airflow-triggerer-claim2
        - name: airflow-triggerer-claim4
          persistentVolumeClaim:
            claimName: airflow-triggerer-claim4
