apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
  labels:
    io.kompose.service: airflow-webserver
    app.kubernetes.io/managed-by: Helm
  name: airflow-webserver
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: airflow-webserver
