apiVersion: v1
kind: Service
metadata:
  name: fastapi-api
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    io.kompose.service: fastapi-api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: fastapi-api
