apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
  labels:
    io.kompose.service: mlflow-server
    app.kubernetes.io/managed-by: Helm
  name: mlflow-server
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 6000
  selector:
    io.kompose.service: mlflow-server
