apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'fastapi-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['fastapi-api:8000']

      - job_name: 'streamlit'
        metrics_path: /metrics
        static_configs:
          - targets: ['streamlit:8502']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
