apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
spec:
  selector:
    app: airflow-webserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.airflow.webPort }}
  type: ClusterIP
