apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.airflow.ports.web.containerPort }}
  type: ClusterIP
