apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
    - name: "8502"
      port: 8502
      targetPort: 8502
  type: ClusterIP
