apiVersion: v1
kind: Service
metadata:
  name: streamlit
  annotations:
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: streamlit
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
    - name: "8502"
      port: 8502
      targetPort: 8502
  selector:
    io.kompose.service: streamlit
