apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
    meta.helm.sh/release-name: my-release1
    meta.helm.sh/release-namespace: default
  labels:
    io.kompose.service: streamlit
    app.kubernetes.io/managed-by: Helm
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - image: streamlit
          name: streamlit
          ports:
            - containerPort: 8501
              protocol: TCP
            - containerPort: 8502
              protocol: TCP
      restartPolicy: Always
