apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: streamlit
    app.kubernetes.io/managed-by: Helm
  name: streamlit
spec:
  replicas: {{ .Values.streamlit.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - image: {{ .Values.streamlit.image | default "streamlit" }}
          name: streamlit
          ports:
            - containerPort: 8501
              protocol: TCP
            - containerPort: 8502
              protocol: TCP
