apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: airflow-webserver
    spec:
      containers:
        - args:
            - webserver
          env:
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS
              value: content-type, origin, authorization, accept
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS
              value: GET, POST, OPTIONS, DELETE
            - name: AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS
              value: '*'
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "true"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_DEFAULT_REGION
            - name: AWS_SECRET_ACCESS_KEY
            - name: _PIP_ADDITIONAL_REQUIREMENTS
          image: airflow-webserver
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: airflow-webserver
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            runAsGroup: 0
            runAsUser: 50000
          volumeMounts:
            - mountPath: /opt/airflow/plugins
              name: airflow-webserver-claim2
      restartPolicy: Always
      volumes:
        - name: airflow-webserver-claim2
          persistentVolumeClaim:
            claimName: airflow-webserver-claim2
