FROM python:3.9-slim

WORKDIR /mlflow

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

EXPOSE 6000
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "6000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
