apiVersion: v1
data:
  Dockerfile.airflow: |
    FROM apache/airflow:2.9.0-python3.10

    # Install system dependencies
    USER root
    RUN apt-get update && apt-get install -y \
        cmake \
        build-essential \
        libpq-dev \
        pkg-config \
        libxmlsec1-dev \
        libssl-dev \
        libxml2-dev \
        libxslt-dev \
        zlib1g-dev \
        && rm -rf /var/lib/apt/lists/*

    # Switch back to airflow user
    USER airflow

    # Upgrade pip and install specific versions of setuptools and wheel
    RUN pip install --upgrade pip
    #    && pip install setuptools==75.8.0 wheel==0.45.1

    # install additional requirements
    COPY requirements.txt /tmp/requirements.txt

    RUN pip install --no-cache-dir -r /tmp/requirements.txt
  requirements.txt: |
    # Core Airflow
    apache-airflow==2.9.0
    apache-airflow-providers-amazon==9.0.0
    apache-airflow-providers-postgres==5.6.0
    apache-airflow-providers-smtp==1.8.0
    pendulum==2.1.2
    sqlalchemy==1.4.52
    psycopg2-binary==2.9.10

    # ML & Tracking
    mlflow==2.7.0
    protobuf==4.25.3
    boto3==1.36.12
    s3fs==2024.3.1

    # Torch & Vision
    torch==2.1.2
    torchvision==0.16.2
    pillow==10.3.0

    # Utilitaires
    pyarrow==13.0.0

    # Prometheus
    prometheus-client==0.16.0
kind: ConfigMap
metadata:
  name: airflow-init-cm0
