apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: {{ index .Values.service.port 0 }}
      targetPort: 9000
      nodePort: {{ index .Values.service.nodePort 0 }}  # Accessible via http://localhost:30900 (S3)
    - name: console
      port: {{ index .Values.service.port 1 }}
      targetPort: 9001
      nodePort: {{ index .Values.service.nodePort 1 }}  # Accessible via http://localhost:30901 (UI Web)
  type: {{ .Values.service.type }}