replicaCount: 1

images:
  airflow:
    repository: your_docker_hub/mlops_classifiimage-airflow-custom
    tag: latest
    pullPolicy: IfNotPresent

postgres:
  conn: postgresql+psycopg2://airflow:airflow@postgres/airflow

airflow:
  executor: LocalExecutor
  loadExamples: "false"
  databaseUrl: postgresql+psycopg2://airflow:airflow@postgres/airflow
  webUser: airflow
  webPassword: airflow

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://minio.default.svc.cluster.local:9000
  bucket: image-dandelion-grass
