FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git curl unzip && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# On copie tout le dossier src (y compris main.py et model.py)
COPY src/ ./src
COPY api/main.py ./main.py

# On dit à uvicorn de chercher depuis le module src
#ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
